Connection error occurred,"HTTPConnectionPool(host='191.37.183.209', port=60139): Max retries exceeded with url: http://www.i28.com/jordan-%E4%B9%94%E4%B8%B9-c-995/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f620ac0fda0>, 'Connection to 191.37.183.209 timed out. (connect timeout=10.48)'))"
Connection error occurred;HTTPConnectionPool(host='51.254.152.142', port=80): Max retries exceeded with url: http://www.i28.com/jordan-%E4%B9%94%E4%B8%B9-c-995/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fd2c4a38208>, 'Connection to 51.254.152.142 timed out. (connect timeout=15.2)'))
2019-07-10 19:03:22.487308;Connection error occurred;HTTPConnectionPool(host='191.37.183.209', port=60139): Max retries exceeded with url: http://www.i28.com/adidas-%E8%B7%91%E6%AD%A5%E9%9E%8B-c-987/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f0a48659080>, 'Connection to 191.37.183.209 timed out. (connect timeout=10.48)'))
2019-07-10 19:03:58.315060;Connection error occurred;HTTPConnectionPool(host='47.52.229.183', port=3128): Read timed out.
2019-07-10 19:04:13.545648;Connection error occurred;HTTPConnectionPool(host='45.224.44.15', port=8080): Max retries exceeded with url: http://www.i28.com/adidas-%E8%B7%91%E6%AD%A5%E9%9E%8B-c-987/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f0a48659588>, 'Connection to 45.224.44.15 timed out. (connect timeout=15.2)'))
2019-07-10 19:04:35.147081;Connection error occurred;HTTPConnectionPool(host='188.235.107.77', port=60205): Max retries exceeded with url: http://www.i28.com/adidas-boost-c-983/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f0a482259b0>, 'Connection to 188.235.107.77 timed out. (connect timeout=12.6)'))
2019-07-10 19:04:45.532295;Connection error occurred;HTTPConnectionPool(host='200.127.155.221', port=8080): Max retries exceeded with url: http://www.i28.com/adidas-boost-c-983/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f0a48231278>, 'Connection to 200.127.155.221 timed out. (connect timeout=10.36)'))
2019-07-10 19:04:53.842470;Connection error occurred;HTTPConnectionPool(host='34.90.87.201', port=80): Max retries exceeded with url: http://www.i28.com/adidas-nmd-c-1032/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f0a480437b8>, 'Connection to 34.90.87.201 timed out. (connect timeout=5.44)'))
2019-07-10 19:05:05.067099;Connection error occurred;HTTPConnectionPool(host='201.49.83.34', port=80): Max retries exceeded with url: http://www.i28.com/adidas-nmd-c-1032/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f0a47fcd0f0>, 'Connection to 201.49.83.34 timed out. (connect timeout=11.120000000000001)'))
2019-07-10 19:05:05.203702;Connection error occurred;HTTPConnectionPool(host='77.77.17.48', port=51368): Max retries exceeded with url: http://www.i28.com/adidas-nmd-c-1032/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0a4823bf60>: Failed to establish a new connection: [Errno 111] Connection refused')))
2019-07-10 19:05:14.859989;Connection error occurred;HTTPConnectionPool(host='185.122.252.122', port=8080): Max retries exceeded with url: http://www.i28.com/adidas-tubular-c-1074/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f0a4813b7f0>, 'Connection to 185.122.252.122 timed out. (connect timeout=7.48)'))
2019-07-10 19:05:15.451819;HTTP error occurred;429 Client Error: Too Many Requests for url: http://www.i28.com/adidas-tubular-c-1074/
2019-07-10 19:05:21.618703;HTTP error occurred;
2019-07-10 19:05:40.501962;Connection error occurred;HTTPConnectionPool(host='116.58.94.162', port=9999): Max retries exceeded with url: http://www.i28.com/adidas-%E4%B8%89%E5%8F%B6%E8%8D%89-c-1034/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f0a48506a20>, 'Connection to 116.58.94.162 timed out. (connect timeout=15.2)'))
2019-07-10 19:05:40.747455;HTTP error occurred;
2019-07-10 19:05:41.136456;HTTP error occurred;
2019-07-10 19:05:41.337218;Connection error occurred;HTTPConnectionPool(host='67.205.149.230', port=8080): Max retries exceeded with url: http://www.i28.com/adidas-%E4%B8%89%E5%8F%B6%E8%8D%89-c-1034/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0a48506f60>: Failed to establish a new connection: [Errno 111] Connection refused')))
2019-07-10 19:05:41.540101;Connection error occurred;HTTPConnectionPool(host='67.205.132.241', port=3128): Max retries exceeded with url: http://www.i28.com/adidas-%E4%B8%89%E5%8F%B6%E8%8D%89-c-1034/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0a48506748>: Failed to establish a new connection: [Errno 111] Connection refused')))
2019-07-10 19:05:41.949060;HTTP error occurred;
2019-07-10 19:05:42.451964;HTTP error occurred;
2019-07-10 19:05:42.952861;HTTP error occurred;
2019-07-10 19:05:43.210833;Connection error occurred;HTTPConnectionPool(host='138.197.204.55', port=8080): Max retries exceeded with url: http://www.i28.com/adidas-%E4%B8%89%E5%8F%B6%E8%8D%89-c-1034/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0a48491438>: Failed to establish a new connection: [Errno 111] Connection refused')))
2019-07-10 19:05:43.471077;Connection error occurred;HTTPConnectionPool(host='138.197.222.35', port=8080): Max retries exceeded with url: http://www.i28.com/adidas-%E4%B8%89%E5%8F%B6%E8%8D%89-c-1034/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0a484a1048>: Failed to establish a new connection: [Errno 111] Connection refused')))
2019-07-10 19:05:43.975702;HTTP error occurred;
2019-07-10 19:05:44.231409;Connection error occurred;HTTPConnectionPool(host='138.197.222.35', port=3128): Max retries exceeded with url: http://www.i28.com/adidas-%E4%B8%89%E5%8F%B6%E8%8D%89-c-1034/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0a484a1198>: Failed to establish a new connection: [Errno 111] Connection refused')))
2019-07-10 19:05:44.733428;HTTP error occurred;
2019-07-10 19:05:45.123923;HTTP error occurred;
2019-07-10 19:05:45.502539;HTTP error occurred;
2019-07-10 19:05:45.883241;HTTP error occurred;
2019-07-10 19:05:46.130563;HTTP error occurred;
2019-07-10 19:05:46.329784;Connection error occurred;HTTPConnectionPool(host='138.197.157.44', port=3128): Max retries exceeded with url: http://www.i28.com/adidas-%E4%B8%89%E5%8F%B6%E8%8D%89-c-1034/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0a484a1a20>: Failed to establish a new connection: [Errno 111] Connection refused')))
2019-07-10 19:05:48.378646;Connection error occurred;('Connection aborted.', BadStatusLine('\x00[\x00\x00\x00\x00\x00\x00'))
2019-07-10 19:05:48.788246;Connection error occurred;HTTPConnectionPool(host='138.197.157.32', port=1080): Max retries exceeded with url: http://www.i28.com/adidas-%E4%B8%89%E5%8F%B6%E8%8D%89-c-1034/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-10 19:05:49.018014;HTTP error occurred;
2019-07-10 19:05:49.259879;HTTP error occurred;
2019-07-10 19:05:49.511097;HTTP error occurred;
2019-07-10 19:05:49.756826;HTTP error occurred;
2019-07-10 19:05:50.003969;HTTP error occurred;
2019-07-10 19:06:03.312523;HTTP error occurred;500 Server Error: Internal Server Error for url: http://www.i28.com/nike-%E7%AF%AE%E7%90%83%E9%9E%8B-c-1125/
2019-07-10 19:06:15.256737;Connection error occurred;HTTPConnectionPool(host='190.109.167.9', port=57608): Max retries exceeded with url: http://www.i28.com/nike-%E7%AF%AE%E7%90%83%E9%9E%8B-c-1125/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f0a487aed30>, 'Connection to 190.109.167.9 timed out. (connect timeout=11.92)'))
2019-07-10 19:09:06.724824;Connection error occurred;HTTPConnectionPool(host='191.37.183.209', port=60139): Max retries exceeded with url: http://www.i28.com/adidas-%E8%B7%91%E6%AD%A5%E9%9E%8B-c-987/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fdae901c080>, 'Connection to 191.37.183.209 timed out. (connect timeout=10.48)'))
2019-07-10 19:09:38.522426;Connection error occurred;HTTPConnectionPool(host='47.52.229.183', port=3128): Read timed out.
2019-07-10 19:33:29.590061;Time error occurred;HTTPConnectionPool(host='51.254.152.142', port=80): Read timed out. (read timeout=25.4)
2019-07-10 19:34:14.803702;Connection error occurred;HTTPConnectionPool(host='47.52.229.183', port=3128): Read timed out.
2019-07-10 19:34:30.026997;Connection error occurred;HTTPConnectionPool(host='45.224.44.15', port=8080): Max retries exceeded with url: http://www.i28.com/adidas-%E8%B7%91%E6%AD%A5%E9%9E%8B-c-987/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6b2dc1f198>, 'Connection to 45.224.44.15 timed out. (connect timeout=15.2)'))
2019-07-10 19:34:42.374622;Connection error occurred;HTTPConnectionPool(host='46.167.206.116', port=8080): Max retries exceeded with url: http://www.i28.com/adidas-%E8%B7%91%E6%AD%A5%E9%9E%8B-c-987/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6b2dc1f828>, 'Connection to 46.167.206.116 timed out. (connect timeout=12.32)'))
2019-07-10 19:35:06.657432;Connection error occurred;HTTPConnectionPool(host='200.127.155.221', port=8080): Max retries exceeded with url: http://www.i28.com/adidas-boost-c-983/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6b2d7e9978>, 'Connection to 200.127.155.221 timed out. (connect timeout=10.36)'))
2019-07-10 19:35:13.599538;Connection error occurred;HTTPConnectionPool(host='41.65.186.166', port=8080): Max retries exceeded with url: http://www.i28.com/adidas-boost-c-983/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6b2d7f52b0>, 'Connection to 41.65.186.166 timed out. (connect timeout=6.92)'))
2019-07-10 19:35:19.062857;Connection error occurred;HTTPConnectionPool(host='34.90.87.201', port=80): Max retries exceeded with url: http://www.i28.com/adidas-boost-c-983/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6b2d7f5b38>, 'Connection to 34.90.87.201 timed out. (connect timeout=5.44)'))
2019-07-10 19:35:25.798828;Connection error occurred;HTTPConnectionPool(host='77.77.17.48', port=51368): Max retries exceeded with url: http://www.i28.com/adidas-nmd-c-1032/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6b2d5fda20>: Failed to establish a new connection: [Errno 111] Connection refused')))
2019-07-10 19:35:33.705401;HTTP error occurred;429 Client Error: Too Many Requests for url: http://www.i28.com/adidas-yeezy-c-985/
2019-07-10 19:35:36.207059;HTTP error occurred;
2019-07-10 19:36:04.703246;Connection error occurred;HTTPConnectionPool(host='116.58.94.162', port=9999): Max retries exceeded with url: http://www.i28.com/nike-%E7%AF%AE%E7%90%83%E9%9E%8B-c-1125/ (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer')))
2019-07-10 19:36:04.946617;HTTP error occurred;
2019-07-10 19:36:05.331926;HTTP error occurred;
2019-07-10 19:36:05.526226;Connection error occurred;HTTPConnectionPool(host='67.205.149.230', port=8080): Max retries exceeded with url: http://www.i28.com/nike-%E7%AF%AE%E7%90%83%E9%9E%8B-c-1125/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6b2d6c0128>: Failed to establish a new connection: [Errno 111] Connection refused')))
2019-07-10 19:36:05.721416;Connection error occurred;HTTPConnectionPool(host='67.205.132.241', port=3128): Max retries exceeded with url: http://www.i28.com/nike-%E7%AF%AE%E7%90%83%E9%9E%8B-c-1125/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6b2d6c0a90>: Failed to establish a new connection: [Errno 111] Connection refused')))
2019-07-10 19:36:06.150300;HTTP error occurred;
2019-07-10 19:36:06.665702;HTTP error occurred;
2019-07-10 19:36:07.166887;HTTP error occurred;
2019-07-10 19:36:07.435770;Connection error occurred;HTTPConnectionPool(host='138.197.204.55', port=8080): Max retries exceeded with url: http://www.i28.com/nike-%E7%AF%AE%E7%90%83%E9%9E%8B-c-1125/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6b2d6c6400>: Failed to establish a new connection: [Errno 111] Connection refused')))
2019-07-10 19:36:07.697501;Connection error occurred;HTTPConnectionPool(host='138.197.222.35', port=8080): Max retries exceeded with url: http://www.i28.com/nike-%E7%AF%AE%E7%90%83%E9%9E%8B-c-1125/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6b2de2acc0>: Failed to establish a new connection: [Errno 111] Connection refused')))
2019-07-10 19:36:08.215043;HTTP error occurred;
2019-07-10 19:36:08.479966;Connection error occurred;HTTPConnectionPool(host='138.197.222.35', port=3128): Max retries exceeded with url: http://www.i28.com/nike-%E7%AF%AE%E7%90%83%E9%9E%8B-c-1125/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6b2d6c03c8>: Failed to establish a new connection: [Errno 111] Connection refused')))
2019-07-10 19:36:08.982113;HTTP error occurred;
2019-07-10 19:36:09.373722;HTTP error occurred;
2019-07-10 19:36:09.756058;HTTP error occurred;
2019-07-10 19:36:10.135366;HTTP error occurred;
2019-07-10 19:36:10.380803;HTTP error occurred;
2019-07-10 19:36:10.595277;Connection error occurred;HTTPConnectionPool(host='138.197.157.44', port=3128): Max retries exceeded with url: http://www.i28.com/nike-%E7%AF%AE%E7%90%83%E9%9E%8B-c-1125/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6b2d6c0278>: Failed to establish a new connection: [Errno 111] Connection refused')))
2019-07-10 19:36:12.706049;Connection error occurred;('Connection aborted.', BadStatusLine('\x00[\x00\x00\x00\x00\x00\x00'))
2019-07-10 19:36:13.116916;Connection error occurred;HTTPConnectionPool(host='138.197.157.32', port=1080): Max retries exceeded with url: http://www.i28.com/nike-%E7%AF%AE%E7%90%83%E9%9E%8B-c-1125/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-10 19:36:13.352510;HTTP error occurred;
2019-07-10 19:36:13.586608;HTTP error occurred;
2019-07-10 19:36:13.822711;HTTP error occurred;
2019-07-10 19:36:14.087681;HTTP error occurred;
2019-07-10 19:36:14.334526;HTTP error occurred;
2019-07-10 19:36:15.389322;Connection error occurred;HTTPConnectionPool(host='95.65.73.200', port=48368): Max retries exceeded with url: http://www.i28.com/nike-%E7%AF%AE%E7%90%83%E9%9E%8B-c-1125/ (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer')))
2019-07-10 19:36:29.427052;Connection error occurred;HTTPConnectionPool(host='190.109.167.9', port=57608): Max retries exceeded with url: http://www.i28.com/nike-%E6%BB%91%E6%9D%BF%E9%9E%8B-c-1008/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6b2d3f3208>, 'Connection to 190.109.167.9 timed out. (connect timeout=11.92)'))
2019-07-10 19:36:53.909898;Connection error occurred;HTTPConnectionPool(host='190.12.58.187', port=53281): Max retries exceeded with url: http://www.i28.com/nike-%E6%B0%94%E5%9E%AB%E9%9E%8B-c-1001/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6b2d19c7b8>, 'Connection to 190.12.58.187 timed out. (connect timeout=15.2)'))
2019-07-10 19:37:09.126577;Connection error occurred;HTTPConnectionPool(host='45.7.231.243', port=80): Max retries exceeded with url: http://www.i28.com/nike-%E8%B7%91%E6%AD%A5%E9%9E%8B-c-1014/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6b2cf54240>, 'Connection to 45.7.231.243 timed out. (connect timeout=7.5600000000000005)'))
2019-07-10 19:37:11.062174;Connection error occurred;HTTPConnectionPool(host='117.242.154.73', port=55446): Max retries exceeded with url: http://www.i28.com/nike-%E8%B7%91%E6%AD%A5%E9%9E%8B-c-1014/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-10 19:37:11.592779;HTTP error occurred;502 Server Error: Bad Gateway for url: http://www.i28.com/nike-%E8%B7%91%E6%AD%A5%E9%9E%8B-c-1014/
2019-07-10 19:37:16.848519;Connection error occurred;HTTPConnectionPool(host='94.242.58.14', port=655): Max retries exceeded with url: http://www.i28.com/nike-%E8%B7%91%E6%AD%A5%E9%9E%8B-c-1014/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6b2d1a6208>, 'Connection to 94.242.58.14 timed out. (connect timeout=5.24)'))
2019-07-10 19:37:17.935368;Connection error occurred;HTTPConnectionPool(host='43.251.170.145', port=54948): Max retries exceeded with url: http://www.i28.com/nike-%E8%B7%91%E6%AD%A5%E9%9E%8B-c-1014/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-10 19:37:18.347118;Connection error occurred;HTTPConnectionPool(host='138.197.157.60', port=1080): Max retries exceeded with url: http://www.i28.com/nike-%E8%B7%91%E6%AD%A5%E9%9E%8B-c-1014/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-10 19:37:18.925763;Connection error occurred;HTTPConnectionPool(host='103.228.119.69', port=4145): Max retries exceeded with url: http://www.i28.com/nike-%E8%B7%91%E6%AD%A5%E9%9E%8B-c-1014/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-10 19:37:33.034307;Connection error occurred;HTTPConnectionPool(host='179.222.46.8', port=1080): Max retries exceeded with url: http://www.i28.com/nike-%E8%B7%91%E6%AD%A5%E9%9E%8B-c-1014/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6b2cf69470>, 'Connection to 179.222.46.8 timed out. (connect timeout=14.08)'))
2019-07-10 19:37:43.796621;Connection error occurred;HTTPConnectionPool(host='139.59.169.246', port=1080): Max retries exceeded with url: http://www.i28.com/nike-%E8%BF%90%E5%8A%A8%E9%9E%8B-c-1006/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6b2dc2c208>: Failed to establish a new connection: [Errno 111] Connection refused')))
2019-07-10 19:37:44.295075;Connection error occurred;HTTPConnectionPool(host='138.68.240.218', port=1080): Max retries exceeded with url: http://www.i28.com/nike-%E8%BF%90%E5%8A%A8%E9%9E%8B-c-1006/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-10 19:37:44.803108;Connection error occurred;HTTPConnectionPool(host='138.68.24.145', port=1080): Max retries exceeded with url: http://www.i28.com/nike-%E8%BF%90%E5%8A%A8%E9%9E%8B-c-1006/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-10 19:37:45.714764;Connection error occurred;HTTPConnectionPool(host='122.116.238.22', port=20005): Max retries exceeded with url: http://www.i28.com/nike-%E8%BF%90%E5%8A%A8%E9%9E%8B-c-1006/ (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer')))
2019-07-10 19:37:46.512732;Connection error occurred;HTTPConnectionPool(host='190.128.247.70', port=4145): Max retries exceeded with url: http://www.i28.com/nike-%E8%BF%90%E5%8A%A8%E9%9E%8B-c-1006/ (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer')))
2019-07-10 19:37:48.310797;Connection error occurred;HTTPConnectionPool(host='68.238.56.49', port=64312): Max retries exceeded with url: http://www.i28.com/nike-%E8%BF%90%E5%8A%A8%E9%9E%8B-c-1006/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-10 19:37:55.315441;Connection error occurred;HTTPConnectionPool(host='110.49.101.58', port=1080): Max retries exceeded with url: http://www.i28.com/nike-%E8%BF%90%E5%8A%A8%E9%9E%8B-c-1006/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-10 19:37:55.930475;Connection error occurred;HTTPConnectionPool(host='181.112.159.194', port=56362): Max retries exceeded with url: http://www.i28.com/nike-%E8%BF%90%E5%8A%A8%E9%9E%8B-c-1006/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-10 19:38:00.879416;Connection error occurred;HTTPConnectionPool(host='138.68.41.90', port=1080): Max retries exceeded with url: http://www.i28.com/new-balance-c-997/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-10 19:38:01.293253;Connection error occurred;HTTPConnectionPool(host='138.197.145.103', port=1080): Max retries exceeded with url: http://www.i28.com/new-balance-c-997/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-10 19:38:07.549000;Connection error occurred;HTTPConnectionPool(host='138.68.161.60', port=1080): Max retries exceeded with url: http://www.i28.com/new-balance-c-997/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6b2d30aeb8>, 'Connection to 138.68.161.60 timed out. (connect timeout=6.24)'))
2019-07-10 19:38:16.930278;Connection error occurred;HTTPConnectionPool(host='200.93.224.222', port=4145): Max retries exceeded with url: http://www.i28.com/new-balance-c-997/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6b2d308898>, 'Connection to 200.93.224.222 timed out. (connect timeout=9.36)'))
2019-07-10 19:38:17.752789;Connection error occurred;HTTPConnectionPool(host='103.113.106.152', port=10801): Max retries exceeded with url: http://www.i28.com/new-balance-c-997/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-10 19:38:18.267476;HTTP error occurred;
2019-07-10 19:38:26.770862;Connection error occurred;HTTPConnectionPool(host='200.77.186.197', port=4145): Max retries exceeded with url: http://www.i28.com/under-armour-c-1135/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-10 19:38:30.517018;Connection error occurred;HTTPConnectionPool(host='201.150.21.6', port=4145): Max retries exceeded with url: http://www.i28.com/under-armour-c-1135/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-10 19:38:42.884152;Connection error occurred;HTTPConnectionPool(host='182.160.109.214', port=32908): Max retries exceeded with url: http://www.i28.com/converse-%E5%8C%A1%E5%A8%81-c-991/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-10 19:38:43.265355;HTTP error occurred;
2019-07-10 19:38:43.458845;Connection error occurred;HTTPConnectionPool(host='67.205.132.241', port=8080): Max retries exceeded with url: http://www.i28.com/converse-%E5%8C%A1%E5%A8%81-c-991/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6b2d26d550>: Failed to establish a new connection: [Errno 111] Connection refused')))
2019-07-10 19:38:44.052182;Connection error occurred;HTTPConnectionPool(host='118.179.149.182', port=4145): Max retries exceeded with url: http://www.i28.com/converse-%E5%8C%A1%E5%A8%81-c-991/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-10 19:38:44.814676;Connection error occurred;HTTPConnectionPool(host='103.115.128.6', port=58794): Max retries exceeded with url: http://www.i28.com/converse-%E5%8C%A1%E5%A8%81-c-991/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-10 19:38:49.598876;HTTP error occurred;403 Client Error: Forbidden for url: http://www.i28.com/vans-%E4%B8%87%E6%96%AF-c-1027/
2019-07-10 19:38:49.599713;403 error because of proxy;['119.81.71.27', '119.81.71.27', '31288', '54', '880', '1880252', 'SG', 'Singapore', 'Singapore', '1881', '19', '4', '1', '1', '0', '0']
2019-07-10 19:38:58.337293;Connection error occurred;HTTPConnectionPool(host='103.251.56.29', port=40304): Max retries exceeded with url: http://www.i28.com/vans-%E4%B8%87%E6%96%AF-c-1027/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6b2ddd54e0>, 'Connection to 103.251.56.29 timed out. (connect timeout=8.72)'))
2019-07-10 19:38:58.913814;Connection error occurred;HTTPConnectionPool(host='14.102.115.237', port=4153): Max retries exceeded with url: http://www.i28.com/vans-%E4%B8%87%E6%96%AF-c-1027/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-10 19:38:59.487384;Connection error occurred;HTTPConnectionPool(host='139.59.64.9', port=1080): Max retries exceeded with url: http://www.i28.com/vans-%E4%B8%87%E6%96%AF-c-1027/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-10 19:39:00.017070;Connection error occurred;HTTPConnectionPool(host='139.59.53.107', port=1080): Max retries exceeded with url: http://www.i28.com/vans-%E4%B8%87%E6%96%AF-c-1027/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-10 19:39:00.531150;Connection error occurred;HTTPConnectionPool(host='139.59.53.106', port=1080): Max retries exceeded with url: http://www.i28.com/vans-%E4%B8%87%E6%96%AF-c-1027/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-10 19:39:00.793457;Connection error occurred;HTTPConnectionPool(host='138.197.204.55', port=1080): Max retries exceeded with url: http://www.i28.com/vans-%E4%B8%87%E6%96%AF-c-1027/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6b2daba438>: Failed to establish a new connection: [Errno 111] Connection refused')))
2019-07-10 19:39:01.339991;Connection error occurred;HTTPConnectionPool(host='139.59.109.156', port=1080): Max retries exceeded with url: http://www.i28.com/vans-%E4%B8%87%E6%96%AF-c-1027/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-10 19:39:01.911309;Connection error occurred;HTTPConnectionPool(host='139.59.101.223', port=1080): Max retries exceeded with url: http://www.i28.com/vans-%E4%B8%87%E6%96%AF-c-1027/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-10 19:39:02.183593;Connection error occurred;HTTPConnectionPool(host='139.59.99.63', port=1080): Max retries exceeded with url: http://www.i28.com/vans-%E4%B8%87%E6%96%AF-c-1027/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6b2de425f8>: Failed to establish a new connection: [Errno 111] Connection refused')))
2019-07-10 19:39:02.711750;Connection error occurred;HTTPConnectionPool(host='139.59.99.234', port=1080): Max retries exceeded with url: http://www.i28.com/vans-%E4%B8%87%E6%96%AF-c-1027/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-10 19:39:04.452996;Connection error occurred;HTTPConnectionPool(host='36.89.188.57', port=42812): Max retries exceeded with url: http://www.i28.com/vans-%E4%B8%87%E6%96%AF-c-1027/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-10 19:39:05.040820;Connection error occurred;HTTPConnectionPool(host='110.232.80.234', port=4145): Max retries exceeded with url: http://www.i28.com/vans-%E4%B8%87%E6%96%AF-c-1027/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-10 19:39:05.255508;Connection error occurred;HTTPConnectionPool(host='138.197.157.45', port=1080): Max retries exceeded with url: http://www.i28.com/vans-%E4%B8%87%E6%96%AF-c-1027/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6b2ddd5320>: Failed to establish a new connection: [Errno 111] Connection refused')))
2019-07-10 19:39:05.459314;Connection error occurred;HTTPConnectionPool(host='138.197.157.44', port=1080): Max retries exceeded with url: http://www.i28.com/vans-%E4%B8%87%E6%96%AF-c-1027/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6b2da9c208>: Failed to establish a new connection: [Errno 111] Connection refused')))
2019-07-10 19:39:15.704693;Connection error occurred;HTTPConnectionPool(host='84.208.9.131', port=80): Max retries exceeded with url: http://www.i28.com/asics-%E4%BA%9A%E7%91%9F%E5%A3%AB-c-989/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6b2d7b9128>, 'Connection to 84.208.9.131 timed out. (connect timeout=7.4)'))
2019-07-10 19:39:25.486912;Connection error occurred;HTTPConnectionPool(host='177.184.64.2', port=4145): Max retries exceeded with url: http://www.i28.com/asics-%E4%BA%9A%E7%91%9F%E5%A3%AB-c-989/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6b2d7b9a58>, 'Connection to 177.184.64.2 timed out. (connect timeout=9.76)'))
2019-07-10 19:39:27.315627;Connection error occurred;HTTPConnectionPool(host='202.166.196.6', port=59428): Max retries exceeded with url: http://www.i28.com/asics-%E4%BA%9A%E7%91%9F%E5%A3%AB-c-989/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-10 19:39:27.888693;Connection error occurred;HTTPConnectionPool(host='156.0.229.194', port=42692): Max retries exceeded with url: http://www.i28.com/asics-%E4%BA%9A%E7%91%9F%E5%A3%AB-c-989/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-10 19:39:28.573493;Connection error occurred;HTTPConnectionPool(host='190.224.35.254', port=4145): Max retries exceeded with url: http://www.i28.com/asics-%E4%BA%9A%E7%91%9F%E5%A3%AB-c-989/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-10 19:39:30.229604;Connection error occurred;HTTPConnectionPool(host='200.220.222.91', port=4145): Max retries exceeded with url: http://www.i28.com/asics-%E4%BA%9A%E7%91%9F%E5%A3%AB-c-989/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-10 19:39:31.062019;Connection error occurred;HTTPConnectionPool(host='202.164.211.116', port=64312): Max retries exceeded with url: http://www.i28.com/asics-%E4%BA%9A%E7%91%9F%E5%A3%AB-c-989/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-10 19:39:32.593512;Connection error occurred;HTTPConnectionPool(host='202.160.164.114', port=51372): Max retries exceeded with url: http://www.i28.com/asics-%E4%BA%9A%E7%91%9F%E5%A3%AB-c-989/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-10 19:39:33.324799;Connection error occurred;HTTPConnectionPool(host='125.27.251.171', port=36743): Max retries exceeded with url: http://www.i28.com/asics-%E4%BA%9A%E7%91%9F%E5%A3%AB-c-989/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-10 19:39:40.743030;Connection error occurred;HTTPConnectionPool(host='110.232.255.149', port=50580): Max retries exceeded with url: http://www.i28.com/asics-%E4%BA%9A%E7%91%9F%E5%A3%AB-c-989/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6b2d716160>, 'Connection to 110.232.255.149 timed out. (connect timeout=7.4)'))
2019-07-10 19:39:41.569287;Connection error occurred;HTTPConnectionPool(host='103.30.115.162', port=1080): Max retries exceeded with url: http://www.i28.com/asics-%E4%BA%9A%E7%91%9F%E5%A3%AB-c-989/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-10 19:39:41.798015;Connection error occurred;HTTPConnectionPool(host='66.158.234.120', port=64312): Max retries exceeded with url: http://www.i28.com/asics-%E4%BA%9A%E7%91%9F%E5%A3%AB-c-989/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6b2d7c2668>: Failed to establish a new connection: [Errno 111] Connection refused')))
2019-07-10 19:39:42.377056;Connection error occurred;HTTPConnectionPool(host='119.10.177.90', port=4145): Max retries exceeded with url: http://www.i28.com/asics-%E4%BA%9A%E7%91%9F%E5%A3%AB-c-989/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-10 19:39:51.538655;Connection error occurred;HTTPConnectionPool(host='103.195.37.101', port=4145): Max retries exceeded with url: http://www.i28.com/asics-%E4%BA%9A%E7%91%9F%E5%A3%AB-c-989/ (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer')))
2019-07-10 19:39:52.296336;Connection error occurred;HTTPConnectionPool(host='45.114.74.230', port=44550): Max retries exceeded with url: http://www.i28.com/asics-%E4%BA%9A%E7%91%9F%E5%A3%AB-c-989/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-10 19:39:53.092080;Connection error occurred;HTTPConnectionPool(host='45.114.72.111', port=59311): Max retries exceeded with url: http://www.i28.com/asics-%E4%BA%9A%E7%91%9F%E5%A3%AB-c-989/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-10 19:39:57.012354;Connection error occurred;HTTPConnectionPool(host='45.249.122.6', port=4153): Max retries exceeded with url: http://www.i28.com/asics-%E4%BA%9A%E7%91%9F%E5%A3%AB-c-989/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-10 19:39:57.587224;Connection error occurred;HTTPConnectionPool(host='45.231.252.7', port=4145): Max retries exceeded with url: http://www.i28.com/asics-%E4%BA%9A%E7%91%9F%E5%A3%AB-c-989/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-10 19:39:58.304787;Connection error occurred;HTTPConnectionPool(host='103.76.190.37', port=31756): Max retries exceeded with url: http://www.i28.com/asics-%E4%BA%9A%E7%91%9F%E5%A3%AB-c-989/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-10 19:40:02.294526;Connection error occurred;HTTPConnectionPool(host='82.137.255.48', port=4145): Max retries exceeded with url: http://www.i28.com/asics-%E4%BA%9A%E7%91%9F%E5%A3%AB-c-989/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-10 19:40:03.052324;Connection error occurred;HTTPConnectionPool(host='110.74.201.70', port=4145): Max retries exceeded with url: http://www.i28.com/asics-%E4%BA%9A%E7%91%9F%E5%A3%AB-c-989/ (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer')))
2019-07-10 19:40:03.539408;Connection error occurred;HTTPConnectionPool(host='45.112.57.110', port=53682): Max retries exceeded with url: http://www.i28.com/asics-%E4%BA%9A%E7%91%9F%E5%A3%AB-c-989/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-10 19:40:05.798394;Connection error occurred;HTTPConnectionPool(host='202.166.203.23', port=39054): Max retries exceeded with url: http://www.i28.com/asics-%E4%BA%9A%E7%91%9F%E5%A3%AB-c-989/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-10 19:40:06.546384;Connection error occurred;HTTPConnectionPool(host='221.121.12.238', port=47012): Max retries exceeded with url: http://www.i28.com/asics-%E4%BA%9A%E7%91%9F%E5%A3%AB-c-989/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-10 19:40:08.199505;Connection error occurred;HTTPConnectionPool(host='150.129.111.54', port=45637): Max retries exceeded with url: http://www.i28.com/asics-%E4%BA%9A%E7%91%9F%E5%A3%AB-c-989/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-10 19:40:08.684317;Connection error occurred;HTTPConnectionPool(host='71.180.95.32', port=54321): Max retries exceeded with url: http://www.i28.com/asics-%E4%BA%9A%E7%91%9F%E5%A3%AB-c-989/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-10 19:40:15.503542;Connection error occurred;HTTPConnectionPool(host='103.66.233.149', port=4145): Max retries exceeded with url: http://www.i28.com/asics-%E4%BA%9A%E7%91%9F%E5%A3%AB-c-989/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6b2d7caa58>, 'Connection to 103.66.233.149 timed out. (connect timeout=6.8)'))
2019-07-10 19:40:15.526360;Connection error occurred;HTTPConnectionPool(host='92.245.114.12', port=4145): Max retries exceeded with url: http://www.i28.com/asics-%E4%BA%9A%E7%91%9F%E5%A3%AB-c-989/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-10 19:40:16.069462;HTTP error occurred;
2019-07-10 19:40:16.372614;Connection error occurred;HTTPConnectionPool(host='79.106.35.65', port=1080): Max retries exceeded with url: http://www.i28.com/asics-%E4%BA%9A%E7%91%9F%E5%A3%AB-c-989/ (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer')))
2019-07-10 19:40:18.104689;Connection error occurred;HTTPConnectionPool(host='103.21.160.156', port=39236): Max retries exceeded with url: http://www.i28.com/asics-%E4%BA%9A%E7%91%9F%E5%A3%AB-c-989/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-10 19:40:18.749653;Connection error occurred;HTTPConnectionPool(host='117.206.83.158', port=44550): Max retries exceeded with url: http://www.i28.com/asics-%E4%BA%9A%E7%91%9F%E5%A3%AB-c-989/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-10 19:40:19.680229;Connection error occurred;HTTPConnectionPool(host='103.69.20.43', port=4145): Max retries exceeded with url: http://www.i28.com/asics-%E4%BA%9A%E7%91%9F%E5%A3%AB-c-989/ (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer')))
2019-07-10 19:40:33.070232;Connection error occurred;HTTPConnectionPool(host='185.10.166.8', port=8080): Max retries exceeded with url: http://www.i28.com/asics-%E4%BA%9A%E7%91%9F%E5%A3%AB-c-989/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6b2d716e80>, 'Connection to 185.10.166.8 timed out. (connect timeout=13.36)'))
2019-07-10 19:40:45.419662;Connection error occurred;HTTPConnectionPool(host='198.50.172.167', port=1080): Max retries exceeded with url: http://www.i28.com/asics-%E4%BA%9A%E7%91%9F%E5%A3%AB-c-989/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6b2d7c2780>, 'Connection to 198.50.172.167 timed out. (connect timeout=12.32)'))
2019-07-10 19:41:05.362290;Time error occurred;HTTPConnectionPool(host='198.50.172.165', port=1080): Read timed out. (read timeout=19.72)
2019-07-10 19:41:05.492118;Connection error occurred;HTTPConnectionPool(host='81.144.230.119', port=3128): Max retries exceeded with url: http://www.i28.com/asics-%E4%BA%9A%E7%91%9F%E5%A3%AB-c-989/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6b2d7ca390>: Failed to establish a new connection: [Errno 111] Connection refused')))
2019-07-10 19:41:11.822749;Connection error occurred;HTTPConnectionPool(host='51.75.161.44', port=3128): Max retries exceeded with url: http://www.i28.com/champion-%E5%86%A0%E5%86%9B-c-1310/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6b2d3af470>: Failed to establish a new connection: [Errno 111] Connection refused')))
2019-07-10 19:41:16.021709;Connection error occurred;HTTPConnectionPool(host='95.179.195.168', port=8080): Max retries exceeded with url: http://www.i28.com/ugg-%E9%9B%AA%E5%9C%B0%E9%9D%B4-c-1175/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6b2d241908>: Failed to establish a new connection: [Errno 111] Connection refused')))
2019-07-10 19:41:20.687160;Connection error occurred;HTTPConnectionPool(host='113.11.47.134', port=48031): Max retries exceeded with url: http://www.i28.com/%E5%87%89%E6%8B%96%E9%9E%8B-c-1096/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-10 19:41:28.969048;Connection error occurred;HTTPConnectionPool(host='85.93.47.137', port=8080): Read timed out.
2019-07-10 19:41:29.297519;Connection error occurred;HTTPConnectionPool(host='82.114.82.90', port=56068): Max retries exceeded with url: http://www.i28.com/%E5%87%89%E6%8B%96%E9%9E%8B-c-1096/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-10 19:41:36.747615;Connection error occurred;HTTPConnectionPool(host='139.59.169.246', port=3128): Max retries exceeded with url: http://www.i28.com/%E6%9B%B4%E5%A4%9A%E8%BF%90%E5%8A%A8%E9%9E%8B-c-1319/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6b2d066240>: Failed to establish a new connection: [Errno 111] Connection refused')))
2019-07-10 19:41:36.994905;HTTP error occurred;
2019-07-10 19:41:37.122593;Connection error occurred;HTTPConnectionPool(host='139.59.169.246', port=8080): Max retries exceeded with url: http://www.i28.com/%E6%9B%B4%E5%A4%9A%E8%BF%90%E5%8A%A8%E9%9E%8B-c-1319/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6b2d615b38>: Failed to establish a new connection: [Errno 111] Connection refused')))
2019-07-10 19:41:37.360809;HTTP error occurred;
2019-07-10 19:41:37.600839;HTTP error occurred;
2019-07-10 19:41:37.836469;HTTP error occurred;
2019-07-10 19:41:38.090931;HTTP error occurred;
2019-07-10 19:41:38.347845;HTTP error occurred;
